CREATE TABLE IF NOT EXISTS run (
				id INTEGER PRIMARY KEY AUTOINCREMENT, 
				name TEXT NOT NULL,
				bufo_definition BLOB NOT NULL,
				created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
				ended_at DATETIME, 
				status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS metric (
				id INTEGER PRIMARY KEY AUTOINCREMENT, 
				run_id INTEGER NOT NULL,
				name TEXT NOT NULL,
				value TEXT NOT NULL,
				timestamp DATETIME NOT NULL, 

				FOREIGN KEY (run_id) REFERENCES run(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS error (
				id INTEGER PRIMARY KEY AUTOINCREMENT, 
				run_id INTEGER NOT NULL,
				name TEXT NOT NULL,
				message TEXT NOT NULL,
				timestamp DATETIME NOT NULL,

				FOREIGN KEY (run_id) REFERENCES run(id) ON DELETE CASCADE
);
