name: bufo-test
type: http
parallel: 10
rate: 5
duration: 10
request:
  url: "http://localhost:8000"
  method: "GET"
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
  body: ""
  timeout: 5
